---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: nitrogen
# description will be included in the image's metadata
description: This is a cool dsitro trust me.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: rawhide

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - 
    remove:
      - ptyxis
      - gnome-connections
      - gnome-contacts
      - gnome-maps
      - gnome-logs
      - yelp
      - gnome-tour
      - mediawriter
      - gnome-extensions-app
      - gnome-calculator
      - loupe
      - snapshot
      - baobab

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
      remove:
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

