---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: nitrogen
# description will be included in the image's metadata
description: This is a cool dsitro trust me.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - sushi
      - gnome-disk-utility
    remove:
      - ptyxis
      - yelp
      - gnome-tour
      - firefox
      - firefox-langpacks
      - gnome-shell-extension-common
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-background-logo
      - gnome-classic-session

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Papers
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.font-viewer
        - org.gnome.Epiphany
        - com.mattjakeman.ExtensionManager
        - page.tesk.Refine
        - io.bassi.Amberol
        - org.libreoffice.LibreOffice
    user:
      repo-name: flathub

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

